services:
  pawtucket:
    build: .
    restart: unless-stopped
    volumes:
      - $PWD:/app/apache2/htdocs
      - ${APACHE_LOGS_DIR:-./log}:/app/apache2/logs
      - ${CA_MEDIA_DIR-../collective-access/media}:/app/apache2/htdocs/media
    ports:
      - ${APACHE_LOCALHOST_PORT:-127.0.0.1:8080}:80
networks:
  default:
    external:
      name: ${PROVIDENCE_NETWORK:-providence_default}
